[package]
name = "boa_profiler"
description = "DEPRECATED. Use flamegraph or valgrind instead."
keywords = ["javascript", "js", "compiler", "profiler"]
categories = ["development-tools::profiling"]
version = "0.20.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
profiler = ["dep:measureme", "dep:once_cell", "dep:rustc-hash"]

[dependencies]
measureme = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true, features = ["std"] }
rustc-hash = { workspace = true, optional = true, features = ["std"] }

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
