# docs https://bors.tech/documentation/
status = [
	"Coverage",
	"Build and Test (macos-latest)",
	"Build and Test (windows-latest)",
	"Misc",
]
pr_status = [
	"Coverage",
	"Build and Test (macos-latest)",
	"Build and Test (windows-latest)",
	"Misc",
]
block_labels = [ "blocked" ]
required_approvals = 2
delete_merged_branches = true
use_squash_merge = true
update_base_for_deletes = true
