extend = [
    { path = "./make/ci.toml"}
]

[config]
default_to_workspace = false

[tasks.run-ci]
description = "Run Boa CI locally"
run_task.name = [
    "ci-fmt-check",
    "ci-lint-all-features",
    "ci-lint-no-features"
]

[tasks.build-cli]
command = "cargo"
args = ["build", "-p", "boa_cli"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--emit=files"]

[tasks.test]
command = "cargo"
args = ["test", "${@}"]

[tasks.test262]
command = "cargo"
args = ["run", "@@remove-empty(RELEASE_ARG)", "--bin", "boa_tester", "--", "run", "${@}"]

[tasks.bench-js]
condition = { env_set = [ "BOA_DATA_ROOT" ] }
command = "cargo"
args = ["run", "--bin", "boa", "--release", "--", "@@remove-empty(BOA_DATA_ROOT)bench/bench-v8/combined.js"]

[tasks.insta-test]
install_crate = "cargo-insta"
command = "cargo"
args = ["insta", "test", "-p", "insta-bytecode", "--review"]
dependencies = ["build-cli"]

[tasks.insta-review]
install_crate = "cargo-insta"
command = "cargo"
args = ["insta", "review", "--manifest-path", "./tests/insta-bytecode/Cargo.toml"]
dependencies = ["build-cli"]

[env.development]
RELEASE_ARG=""

[env.profiling]
RELEASE_ARG="--profile=release-dbg"

[env.production]
RELEASE_ARG="--release"
