[package]
name = "scripts"
publish = false
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
cargo_metadata = "0.18.1"
log.workspace = true
simple_logger.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
