[package]
name = "boa_string"
keywords = ["javascript", "js", "string"]
categories = ["parser-implementations", "compilers"]
readme = "../../README.md"
description.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
oscars = { git = "https://github.com/boa-dev/oscars.git", branch = "main", features = ["mark_sweep_branded"], optional = true }
itoa.workspace = true
rustc-hash = { workspace = true, features = ["std"] }
ryu-js.workspace = true

static_assertions.workspace = true
pastey.workspace = true
fast-float2.workspace = true

[lints]
workspace = true

[features]
oscars_backend = ["dep:oscars"]

[package.metadata.docs.rs]
all-features = true
