[package]
name = "test262"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true, features = ["derive"] }
phf = { workspace = true, features = ["macros"] }
rustc-hash = { workspace = true, features = ["std"] }
bitflags.workspace = true
color-eyre.workspace = true
serde_yaml = "0.9.34" # TODO: Track https://github.com/saphyr-rs/saphyr.

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
