[package]
name = "small_map"
keywords = ["small", "map"]
categories = ["data-structures"]
readme = "../../README.md"
description = "Utility library that add SmallMap data structure"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
arrayvec.workspace = true