[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

# TODO: track https://github.com/rust-lang/rust/issues/141626 for a resolution
[target.x86_64-pc-windows-msvc]
rustflags = ['-Csymbol-mangling-version=v0']

[env]
MIRIFLAGS = "-Zmiri-tree-borrows"
