[package]
name = "boa_interop"
description = "Interop utilities for integrating boa with a Rust host."
keywords = ["javascript", "js", "interop"]
categories = ["api-bindings"]
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
boa_engine.workspace = true
boa_gc.workspace = true
rustc-hash = { workspace = true, features = ["std"] }

[lints]
workspace = true
