name: PR Management

on:
  pull_request_target:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: read

jobs:
  manage_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Auto Add Label
        if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize'
        uses: actions/github-script@v8
        with:
          script: |
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            if (labels.data.every(label => label.name != "Waiting On Author")) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['Waiting On Review']
              })
            }


      - name: Auto Remove Label
        if: github.event.action == 'closed'
        uses: actions/github-script@v8
        continue-on-error: true
        with:
          script: |
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'Waiting On Review'
              });
            } catch (error) {
              console.log('Label "Waiting On Review" not found or could not be removed.');
            }

      - name: Auto Assign Milestone
        if: github.event.action == 'opened'
        uses: actions/github-script@v8
        with:
          script: |
            // Fetch open milestones and assign the closest one
            const { data: milestones } = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'due_on',
              direction: 'asc'
            });

            if (milestones.length > 0) {
              const latestMilestone = milestones[0];
              await github.rest.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                milestone: latestMilestone.number
              });
            }
