name: SemVer Checks
run-name: "SemVer Check for PR #${{ github.event.number }} by @${{ github.actor }}"

on:
  pull_request:
    branches:
      - main
      - releases/**

jobs:
  runSemVerCheck:
    name: Check SemVer compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2